title: Jason Sowards # your name (or website title) here
logo: "IMG_9021 (2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  25+ years as an editor in magazine publishing with extensive experience editing and managing B2B content for websites, e-newsletters and social media sites 
  <br><br>
  Has a bachelor's degree in journalism 
  <br><br>
  <a href="https://www.linkedin.com/in/jason-sowards-36b73036/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
